import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 文档信息架构：快速开始 / 用户手册 / 使用示例 / 参考手册。
 *
 * 各分组的文章由对应目录自动生成；新增 Markdown 后无需在此登记。
 * 默认按文件名排序，若需要调整同一分组内的顺序，可选地在 Front Matter
 * 中设置 sidebar_position。
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: '快速开始',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: '用户手册',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'user'}],
    },
    {
      type: 'category',
      label: '使用示例',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'examples'}],
    },
    {
      type: 'category',
      label: '参考手册',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
